# syntax=docker/dockerfile:1
FROM node:22-alpine AS build

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY . .

ARG VITE_TIPS_URL=
ARG VITE_DAYS_PER_YEAR=365
ARG VITE_WEEKEND_DAYS=104
ARG VITE_VACATION_DAYS=30
ARG VITE_PUBLIC_HOLIDAYS=11
ARG VITE_HOURS_PER_WEEK=38
ARG VITE_WORK_DAYS_PER_WEEK=5
ARG VITE_WORK_DAYS_PER_YEAR=
ARG VITE_SALARY_TARIFF=90000
ARG VITE_SALARY_NON_TARIFF=150000
ARG VITE_SALARY_EXECUTIVE=300000
ARG VITE_SALARY_BOARD=3000000

ENV VITE_TIPS_URL=$VITE_TIPS_URL \
    VITE_DAYS_PER_YEAR=$VITE_DAYS_PER_YEAR \
    VITE_WEEKEND_DAYS=$VITE_WEEKEND_DAYS \
    VITE_VACATION_DAYS=$VITE_VACATION_DAYS \
    VITE_PUBLIC_HOLIDAYS=$VITE_PUBLIC_HOLIDAYS \
    VITE_HOURS_PER_WEEK=$VITE_HOURS_PER_WEEK \
    VITE_WORK_DAYS_PER_WEEK=$VITE_WORK_DAYS_PER_WEEK \
    VITE_WORK_DAYS_PER_YEAR=$VITE_WORK_DAYS_PER_YEAR \
    VITE_SALARY_TARIFF=$VITE_SALARY_TARIFF \
    VITE_SALARY_NON_TARIFF=$VITE_SALARY_NON_TARIFF \
    VITE_SALARY_EXECUTIVE=$VITE_SALARY_EXECUTIVE \
    VITE_SALARY_BOARD=$VITE_SALARY_BOARD

RUN npm run build

FROM nginx:1.27-alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html

HEALTHCHECK --interval=30s --timeout=5s --retries=3 --start-period=10s \
  CMD wget -qO- http://127.0.0.1/ || exit 1

EXPOSE 80
